# Content-related messages

content.content_missing=El contenido del nodo no existe: \n\
		nodo: {0} \n\
		lector: {1}  \n\
		Por favor contacte con el administrador del sistema.
content.http_reader.err.check_cluster=Por favor asegurate que 'replicateUpdates'  y  'replicateUpdatesViaCopy' esta habilitado en la cache 'org.alfresco.cache.ticketsCache'
content.http_reader.err.no_authentication=El lector HTTP no se pudo autenticar en el servidor remoto.{0}
content.http_reader.err.no_connection=Imposible conectar al Servidor Remoto de Alfresco via HTTP:{0}
content.http_reader.err.unrecognized=Se ha producido un error inesperado al intentar descargar el contenido del servidor remoto:\n\
		Servidor:{0}\n\
		Contenido:{1}\n\
		Respuesta HTTP: {2}
content.runtime_exec.property_moved=La propiedad ''errorCodes'' se ha movido a la clase ''RuntimeExec''
index.recovery.complete=Recuperación de índices completada.
index.recovery.out_of_date=Los índices no están sincronizados con la base de datos.
index.recovery.progress=\t{0} % completado.
index.recovery.starting=Iniciada la recuperación de índices: {0} transaciones.
index.recovery.terminated=Recuperación de índices finalizada.
metadata.extraction.err.type_conversion=Ha fallado la extracción de metadata porque no se ha procido un error al convertir un valor extraido al tipo requrido:\n\
		   Extractor: {0} \n\
		   QName Propiedad Destino: {1} \n\
		   Tipo Requerido: {2} \n\
		   Valor Extraido: {3}
